# Generated by Django 5.2.8 on 2025-11-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0004_alter_profile_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("url", models.URLField(max_length=2000)),
                ("image", models.ImageField(upload_to="images/%Y/%m/%d/")),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_created",
                        to="account.profile",
                    ),
                ),
                (
                    "users_like",
                    models.ManyToManyField(
                        blank=True, related_name="images_liked", to="account.profile"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="image_image_created_f4c9e6_idx"
                    )
                ],
            },
        ),
    ]
