# Generated by Django 5.2.8 on 2025-11-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, unique=True),
        ),
    ]
